name: Deploy Preview

on: [pull_request]

env:
  # NEON_DATABASE_USERNAME: ${{ secrets.PG_USERNAME }} # change this to your database username
  # NEON_DATABASE_NAME: ${{ secrets.PG_DATABASE }} # change this to your database name
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required for commenting on pull requests for private repos
  # NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }} # You can find this in your project settings

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          # project_id: ${{ env.NEON_PROJECT_ID }} # optional, can be specified in .neon file in project dir or
          # parent: previews_template # optional (defaults to your default branch)
          branch_name: preview/pr-${{ github.event.number }}-${{ steps.branch-name.outputs.current_branch }}
          # username: ${{ env.NEON_DATABASE_USERNAME }} # optional, defaults to a random role in a project, not needed for single-role projects
          # database: ${{ env.NEON_DATABASE_NAME }} # optional (defaults to neondb)
          api_key: ${{ secrets.NEON_API_KEY }} # Generate a an API key in your account settings

      - name: Add the connection string to wrangler
        id: add-neon-env-wrangler
        run: |
          echo "[vars]" >> wrangler.toml
          echo "DATABASE_URL = \"${{ steps.create-branch.outputs.db_url_with_pooler }}\"" >> wrangler.toml

      - name: Setup Node.js
        id: setup-node-js
        uses: actions/setup-node@v4
        
      - name: Install Dependencies
        id: install-deps
        run: npm install
        
      - name: Run Migrations
        id: run-miggrations
        run: npm run db:migrate 
        env:
          DATABASE_URL: "${{ steps.create-branch.outputs.db_url_with_pooler }}"

      - name: Build the project
        id: build-project
        run: npm run build
      
      - name: Publish
        id: publish-to-cf
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: ${{ steps.branch-name.outputs.current_branch }}
          # Optional: Change the working directory
          # workingDirectory: dist
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          # wranglerVersion: '3'

      - name: Add neon console link to summary
        id: add_console_link
        run: |
          echo  "# Neon Workflow! :rocket: " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "| Neon |  |\n| --- | --- |\n| Branch | https://console.neon.tech/app/projects/'${{ env.NEON_PROJECT_ID }}/branches/'${{ steps.branch-name.outputs.branch_id }} |" >> $GITHUB_STEP_SUMMARY

      - name: Schema diff
        id: run_schema_diff
        run: |
          echo  "## Schema diff" >> $GITHUB_STEP_SUMMARY
          (echo '```'; npx neonctl --no-color branches schema-diff main preview/pr-${{ github.event.number }}-${{ steps.branch-name.outputs.current_branch }} --api-key ${{ secrets.NEON_API_KEY }} ; echo '```') >> $GITHUB_STEP_SUMMARY
